name: CI-testing

on: 
  pull_request:
    types: [opened, edited]
  workflow_dispatch:

jobs:
  CI-testing:
    runs-on: [self-hosted]

    steps:
    - name: checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 2
    
    - name: code-style
      run:  sh/run_test_format.sh
      
    - name: setup
      run: ./bootstrap && ./configure
      
    - name: make
      run: make -j4
      
    - name: check
      run: TESTSUITEFLAGS=-j4 make check -j4 || (sh/after_failure.sh && false)
